/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openpanodroid_panoutils_android_CubicPanoNative */

#ifndef _Included_org_openpanodroid_panoutils_android_CubicPanoNative
#define _Included_org_openpanodroid_panoutils_android_CubicPanoNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openpanodroid_panoutils_android_CubicPanoNative
 * Method:    calculateCubeSide
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_org_openpanodroid_panoutils_android_CubicPanoNative_calculateCubeSide
  (JNIEnv *, jclass, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
