/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openpanodroid_panoutils_android_CubicPanoNative_TextureFaces */

#ifndef _Included_org_openpanodroid_panoutils_android_CubicPanoNative_TextureFaces
#define _Included_org_openpanodroid_panoutils_android_CubicPanoNative_TextureFaces
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
